services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "exemples"
      POSTGRES_USER: "user"
      POSTGRES_DB: "teste"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
