# Use a imagem oficial do PostgreSQL como base
FROM postgres:latest

# Define variáveis de ambiente para configurar o PostgreSQL
ENV POSTGRES_USER=user
ENV POSTGRES_PASSWORD=exemples
ENV POSTGRES_DB=teste

# Copie scripts de inicialização (se necessário)
COPY init.sql /docker-entrypoint-initdb.d/

# Exponha a porta padrão do PostgreSQL
EXPOSE 5432

# Comando padrão para iniciar o PostgreSQL
CMD ["postgres"]
