FROM nginx:latest

# Copie o arquivo de configuração do Nginx para o container
COPY nginx.conf /etc/nginx/nginx.conf

# Crie o diretório onde os vídeos serão armazenados
RUN mkdir -p /var/www/videos

# Copie vídeos para o diretório do container
# Substitua "videos" pelo caminho onde seus vídeos estão armazenados
# COPY videos /var/www/videos

# Exponha a porta 80 para o tráfego HTTP
EXPOSE 80

