version: "2"
services:
  node:
    build: .
    restart: always
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    networks:
      - default
    ports:
      - "8888:8888"
    command: "npm run start"
