services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db_teste
      MYSQL_USER: user
      MYSQL_PASSWORD: naosei
      MYSQL_ROOT_PASSWORD: 12345
      TZ: "America/Sao_Paulo"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
